version: "3"
services:
  api-database:
    image: tutum/mongodb
    container_name: "api-database"
    environment:
      AUTH: "no"
    ports:
      - 27017:27017
      - 28017:28017
  api:
    image: api-ranking-car
    ports:
      - 9091:8080
    links:
      - api-database